/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppEventsRouteImport } from './routes/app/events'
import { Route as AppEvent_detailsRouteImport } from './routes/app/event_details'
import { Route as AppEventParticipantsRouteImport } from './routes/app/$event/participants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/app/home',
  path: '/app/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/app/events',
  path: '/app/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEvent_detailsRoute = AppEvent_detailsRouteImport.update({
  id: '/app/event_details',
  path: '/app/event_details',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventParticipantsRoute = AppEventParticipantsRouteImport.update({
  id: '/app/$event/participants',
  path: '/app/$event/participants',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/event_details': typeof AppEvent_detailsRoute
  '/app/events': typeof AppEventsRoute
  '/app/home': typeof AppHomeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/$event/participants': typeof AppEventParticipantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/event_details': typeof AppEvent_detailsRoute
  '/app/events': typeof AppEventsRoute
  '/app/home': typeof AppHomeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/$event/participants': typeof AppEventParticipantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/event_details': typeof AppEvent_detailsRoute
  '/app/events': typeof AppEventsRoute
  '/app/home': typeof AppHomeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/$event/participants': typeof AppEventParticipantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/event_details'
    | '/app/events'
    | '/app/home'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/app/$event/participants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/event_details'
    | '/app/events'
    | '/app/home'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/app/$event/participants'
  id:
    | '__root__'
    | '/'
    | '/app/event_details'
    | '/app/events'
    | '/app/home'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/app/$event/participants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppEvent_detailsRoute: typeof AppEvent_detailsRoute
  AppEventsRoute: typeof AppEventsRoute
  AppHomeRoute: typeof AppHomeRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AppEventParticipantsRoute: typeof AppEventParticipantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/home': {
      id: '/app/home'
      path: '/app/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/events': {
      id: '/app/events'
      path: '/app/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/event_details': {
      id: '/app/event_details'
      path: '/app/event_details'
      fullPath: '/app/event_details'
      preLoaderRoute: typeof AppEvent_detailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$event/participants': {
      id: '/app/$event/participants'
      path: '/app/$event/participants'
      fullPath: '/app/$event/participants'
      preLoaderRoute: typeof AppEventParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppEvent_detailsRoute: AppEvent_detailsRoute,
  AppEventsRoute: AppEventsRoute,
  AppHomeRoute: AppHomeRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AppEventParticipantsRoute: AppEventParticipantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
