/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppTemplatesRouteImport } from './routes/app/templates'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppEventsRouteImport } from './routes/app/events'
import { Route as AppEvent_detailsRouteImport } from './routes/app/event_details'
import { Route as AppTemplateCreateRouteImport } from './routes/app/template/create'
import { Route as AppTemplateTemplateRouteImport } from './routes/app/$template/template'
import { Route as AppEventParticipantsRouteImport } from './routes/app/$event/participants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/app/templates',
  path: '/app/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/app/events',
  path: '/app/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEvent_detailsRoute = AppEvent_detailsRouteImport.update({
  id: '/app/event_details',
  path: '/app/event_details',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplateCreateRoute = AppTemplateCreateRouteImport.update({
  id: '/app/template/create',
  path: '/app/template/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplateTemplateRoute = AppTemplateTemplateRouteImport.update({
  id: '/app/$template/template',
  path: '/app/$template/template',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventParticipantsRoute = AppEventParticipantsRouteImport.update({
  id: '/app/$event/participants',
  path: '/app/$event/participants',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/event_details': typeof AppEvent_detailsRoute
  '/app/events': typeof AppEventsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/templates': typeof AppTemplatesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/$event/participants': typeof AppEventParticipantsRoute
  '/app/$template/template': typeof AppTemplateTemplateRoute
  '/app/template/create': typeof AppTemplateCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/event_details': typeof AppEvent_detailsRoute
  '/app/events': typeof AppEventsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/templates': typeof AppTemplatesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/$event/participants': typeof AppEventParticipantsRoute
  '/app/$template/template': typeof AppTemplateTemplateRoute
  '/app/template/create': typeof AppTemplateCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/event_details': typeof AppEvent_detailsRoute
  '/app/events': typeof AppEventsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/templates': typeof AppTemplatesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/$event/participants': typeof AppEventParticipantsRoute
  '/app/$template/template': typeof AppTemplateTemplateRoute
  '/app/template/create': typeof AppTemplateCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/event_details'
    | '/app/events'
    | '/app/profile'
    | '/app/templates'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/app/$event/participants'
    | '/app/$template/template'
    | '/app/template/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/event_details'
    | '/app/events'
    | '/app/profile'
    | '/app/templates'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/app/$event/participants'
    | '/app/$template/template'
    | '/app/template/create'
  id:
    | '__root__'
    | '/'
    | '/app/event_details'
    | '/app/events'
    | '/app/profile'
    | '/app/templates'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/app/$event/participants'
    | '/app/$template/template'
    | '/app/template/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppEvent_detailsRoute: typeof AppEvent_detailsRoute
  AppEventsRoute: typeof AppEventsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AppEventParticipantsRoute: typeof AppEventParticipantsRoute
  AppTemplateTemplateRoute: typeof AppTemplateTemplateRoute
  AppTemplateCreateRoute: typeof AppTemplateCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/app/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/events': {
      id: '/app/events'
      path: '/app/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/event_details': {
      id: '/app/event_details'
      path: '/app/event_details'
      fullPath: '/app/event_details'
      preLoaderRoute: typeof AppEvent_detailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/template/create': {
      id: '/app/template/create'
      path: '/app/template/create'
      fullPath: '/app/template/create'
      preLoaderRoute: typeof AppTemplateCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$template/template': {
      id: '/app/$template/template'
      path: '/app/$template/template'
      fullPath: '/app/$template/template'
      preLoaderRoute: typeof AppTemplateTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$event/participants': {
      id: '/app/$event/participants'
      path: '/app/$event/participants'
      fullPath: '/app/$event/participants'
      preLoaderRoute: typeof AppEventParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppEvent_detailsRoute: AppEvent_detailsRoute,
  AppEventsRoute: AppEventsRoute,
  AppProfileRoute: AppProfileRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AppEventParticipantsRoute: AppEventParticipantsRoute,
  AppTemplateTemplateRoute: AppTemplateTemplateRoute,
  AppTemplateCreateRoute: AppTemplateCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
